Fix NoMethodError on nil cookies using Net::HTTP
Deleting the cookie header instead of just setting to nil works around an issue
where `net/http` raises an error in `initialize_http_header`:

    undefined method `strip' for nil:NilClass (NoMethodError)